### ISSUE TITLE
一个小错误 单词1中的例句

### ISSUE THREAD

**Issue by MarchenCreator** [hefengxian/my-ielts#15]
![image](https://github.com/user-attachments/assets/24c174bd-8840-4e43-bade-cf4be33a8270)
如图，单词1中的单词crust的例句：
The crust on the snow was thick enough for us to walk on it
这里应该是 The crust on the snow was thick enough for us walk on it

感觉作者的付出以及努力，这很有用

**Comment by MarchenCreator** [comment]
原句：The crust on the snow was thick enough for to walk on it
修正：The crust on the snow was thick enough for us to walk on it

**Comment by hefengxian** [comment]
非常感谢你的反馈，稍后我将修正这个问题
