### ISSUE TITLE
Missing word 'invent' between 1026-devise and 1027-discover in chapter 6

### ISSUE THREAD

**Issue by guodhu** [hefengxian/my-ielts#7]

**Comment by hefengxian** [comment]
Thank you for your feedback. The missing word has been added

4389e7e21a4c6f50c23324e888a86defc32da31d

Based on your feedback, it looks like you have the same vocabulary book.

Also please star this project!🥹

**Comment by guodhu** [comment]
I don't have the book. I did dictation on Excel and compared them with your words to check my mistakes. That's the reason I can find typos.

**Comment by hefengxian** [comment]
I checked the Linkedin link in your Github profile, it seems you are an awasome individual. you had a strong education background and currently working for a prominent company in Canada.
Your English proficiency seems very high. Why do you still need to learn IELTS? 

By the way, Merry Christmas! 

Hope everything is going well for you in the foreign country

**Comment by guodhu** [comment]
My English is bad. I'm preparing for my first IELTS, which is necessary for the PR application. Merry Christmas!

**Comment by guodhu** [comment]
Thanks for this project. I plan to follow your steps to prepare mine.

**Comment by hefengxian** [comment]
> My English is bad. I'm preparing for my first IELTS, which is necessary for the PR application. Merry Christmas!

I guess so. Getting Canadian PR requires IELTS Gerneral scores.

By the way, I noticed in your LinkedIn profile that no mention of your study experience in Canada. You know, Canada has the PGWP(Post-Graduation Work Permit) policy for international students.

So I'm curious, how did you get your current job and visa? As I know the visas of Canada are not easy to get.

**Comment by guodhu** [comment]
Inner company transfer. My company helped me on the VISA. I worked for the same company before and after I come to Canada.

**Comment by hefengxian** [comment]
> Inner company transfer. My company helped me on the VISA. I worked for the same company before and after I come to Canada.

I get it! Thank you for the reply
