### ISSUE TITLE
Some typo in chapter 14 & 16

### ISSUE THREAD

**Issue by guodhu** [hefengxian/my-ielts#8]
traval -> travel
canel -> canal
résumé -> resume?

**Comment by hefengxian** [comment]
Thank you for your feedback
- travel
- canal 
the typo of these 2 words has been fixed

About word résumé/resume please check Cambridge Dictionary [résumé/resume](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/resume?q=r%C3%A9sum%C3%A9)
- when as noun the spell should be **résumé** the pronounce `UK /ˈrez.juː.meɪ/ US /ˈrez.ə.meɪ/`
- in the book uses spell **résumé**

[9029729](https://github.com/hefengxian/my-ielts/commit/9029729f03d4dddfd436f996c11995725921ab8f)

**Comment by guodhu** [comment]
Thanks a lot for the information. I also cross-checked [Longman](https://www.ldoceonline.com/dictionary/resume), [Merriam-Webster](https://www.merriam-webster.com/dictionary/resume) and [Wikipedia](https://en.wikipedia.org/wiki/R%C3%A9sum%C3%A9). Seems both résumé and resume for noun are correct.
